//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Agreement = new HashSet<Agreement>();
            this.FinancialTransactions = new HashSet<FinancialTransactions>();
            this.MedicalRecord = new HashSet<MedicalRecord>();
        }
    
        public int ID_Employee { get; set; }
        public string LastName_Employee { get; set; }
        public string FirstName_Employee { get; set; }
        public string Patronymic_Employee { get; set; }
        public System.DateTime DB_Employee { get; set; }
        public int ID_Gender { get; set; }
        public string Phone_Employee { get; set; }
        public string Email_Employee { get; set; }
        public string Passport { get; set; }
        public string ResidentialAddress_Employee { get; set; }
        public int ID_Post { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreement { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialTransactions> FinancialTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRecord> MedicalRecord { get; set; }
    }
}
