//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryTests
    {
        public int ID_LT { get; set; }
        public int ID_Pet { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Service { get; set; }
        public string Result_LT { get; set; }
    
        public virtual Pets Pets { get; set; }
        public virtual Service Service { get; set; }
    }
}
