//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int ID_Storage { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public Nullable<int> ShelfLife { get; set; }
        public Nullable<int> ID_Supplier { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
